services:
  client:
    container_name: app-client
    build: ./client
    ports:
      - "3000:3000"
    working_dir: /client
    environment:
      - VITE_API_URL=http://localhost:3001/api/users
    volumes:
      - ./client:/client

  server:
    container_name: app-server
    build: ./server
    ports:
      - "3001:8080"
    working_dir: /server
    volumes:
      - ./server:/server